class PurchaseProduct < ApplicationRecord
	belongs_to :purchase
  has_many :inventories
  belongs_to :product, optional: true
  before_save :create_products
  attr_accessor :product_name, :price, :unit, :categories


  def create_products
  # What I need to do now is to assign the product_id generated by create_products method to purchase_product product_id.

     if product_id.nil?
       Product.create(product_name: product_name, price: price, unit: unit, categories: categories)
       product_id = Product.where("product_name = ?", product_name).ids
     end
  end

  def set_estimated_subtotal
    self.estimated_subtotal = estimated_quantity * estimated_price_per_unit
  end

  def set_actual_subtotal
  	self.actual_subtotal = actual_quantity * actual_price_per_unit
  end

  def self.clean_orphans
    PurchaseProduct.all.each do |pp|
      if pp.purchase.nil?
        pp.destroy
      end
    end
  end

  def display_text
    return "#{purchase_id} - #{product.product_name} - #{purchase.supplier.suppliers_name} - #{purchase.expected_date_of_delivery}"
  end
end
